language: cpp
script: make unit
dist: trusty

env:
  global:
    - CIBW_BUILD='cp36-* cp37-*'
    - CIBW_SKIP='*-manylinux1_i686'
    - CIBW_TEST_REQUIRES='pytest'
    - CIBW_BEFORE_BUILD='pip install "numpy>=1.16" && pip install "pandas>=0.24" && pip install "pytest>=4.3" && pip install cmake'
    - CIBW_TEST_COMMAND='python -m pytest {project}/tests'
    - TWINE_USERNAME=hfmuehleisen

matrix:
  include:

    - os: linux
      name: Python Package

      dist: xenial
      language: python
      python: 3.7

      script:
        - pip install cibuildwheel==0.10.2
        - cd tools/pythonpkg
        - python setup.py sdist
        - mkdir duckdb_tarball && tar xvf dist/duckdb-*.tar.gz --strip-components=1 -C duckdb_tarball
        - cibuildwheel --output-dir wheelhouse duckdb_tarball
        - |
          if [[ $TRAVIS_TAG ]]; then
            pip install twine
            python -m twine upload --skip-existing wheelhouse/*.whl
          fi

    - os: osx
      name: Python Package
      language: generic

      script:
        - pip install cibuildwheel==0.10.2
        - cd tools/pythonpkg
        - python setup.py sdist
        - mkdir duckdb_tarball && tar xvf dist/duckdb-*.tar.gz --strip-components=1 -C duckdb_tarball
        - cibuildwheel --output-dir wheelhouse duckdb_tarball
        - |
          if [[ $TRAVIS_TAG ]]; then
            pip install twine
            python -m twine upload --skip-existing wheelhouse/*.whl
          fi

    - os: windows
      name: Python Package
      language: cpp

      before_install:
        - choco install python --version 3.7.3
        - c:/python37/python.exe -m pip install --upgrade pip
        - c:/python37/python.exe -m pip install "cibuildwheel==0.10.2"

      script:
        - cd tools/pythonpkg
        - c:/python37/python.exe setup.py sdist
        - c:/python37/python.exe -m pytest tests
        - c:/python37/python.exe -m cibuildwheel --platform windows --output-dir wheelhouse duckdb_tarball
        - |
          if [[ $TRAVIS_TAG ]]; then
            c:/python37/python.exe -m pip install twine
            c:/python37/python.exe -m twine upload --skip-existing wheelhouse/*.whl
          fi

before_install:
  - eval "${MATRIX_EVAL}"
