language: cpp
script: make unit
dist: trusty

env:
  global:
    - CIBW_BUILD='cp35-* cp36-* cp37-*'
    - CIBW_TEST_REQUIRES='pytest'
    - CIBW_BEFORE_BUILD='pip install "numpy>=1.16" && pip install "pandas>=0.24" && pip install "pytest>=4.3" && pip install cmake'
    - CIBW_TEST_COMMAND='python -m pytest {project}/tests'
    - TWINE_USERNAME=hfmuehleisen

matrix:
  include:

    - os: linux
      name: Python Package

      dist: xenial
      language: python
      python: 3.7

      script:
        - pip install cibuildwheel==0.10.1
        - cd tools/pythonpkg
        - python setup.py sdist
        - mkdir duckdb_tarball && tar xvf dist/duckdb-*.tar.gz --strip-components=1 -C duckdb_tarball
        - cibuildwheel --output-dir wheelhouse duckdb_tarball
        - |
          if [[ $TRAVIS_TAG ]]; then
            pip install twine
            python -m twine upload --skip-existing wheelhouse/*.whl
          fi

before_install:
  - eval "${MATRIX_EVAL}"
